### ISSUE TITLE
How to install it with jitsi in docker and based on nginx?

### ISSUE THREAD

**Issue by alexmusses** [cketti/jitsi-hacks#6]
Hey there!
Thanks for the great idea of amazing hacks.
How can I add it to an existing jitsi server in docker based on nginx?
Is there any option?

Thanks!

**Comment by cketti** [comment]
I don't use the Docker variant. You'll have to adapt the instructions from https://github.com/cketti/jitsi-hacks/issues/3#issuecomment-739332293

**Comment by alexmusses** [comment]
But it is based on apache and not nginx?

**Comment by cketti** [comment]
There's no turnkey solution. You'll have to do some of the work yourself.
